controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Standard controller to handle the "Command Interface"
    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

# Configuration for the standard velocity controller
joint_group_velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

# Your custom Python driver params (Renamed)
omnidirectional_driver:
  ros__parameters:
    # ----------------------------------------
    # Physical Robot Parameters
    # ----------------------------------------
    robot_radius: 0.115
    wheel_radius: 0.03
    wheel_names: 
      - joint_1
      - joint_2
      - joint_3

    # ----------------------------------------
    # Kinematic Geometry
    # ----------------------------------------
    wheel_angles_deg: [270.0, 30.0, 150.0]
    roller_angle_deg: 0.0